# Generated by Django 2.2.3 on 2020-04-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('level', models.CharField(max_length=256)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tree_db',
            },
        ),
    ]
