# Generated by Django 2.2.3 on 2020-04-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='tree_db2',
        ),
    ]
