# Generated by Django 2.2.3 on 2020-04-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200415_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level0',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
